In [2]:
import numpy as np

In [3]:
a = np.linspace(1,6,6,dtype=np.int32).reshape(2,3)

In [4]:
a

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [5]:
b = np.vstack([a,a])

In [6]:
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [7]:
x,y = np.split(b,[2])

In [8]:
x

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [9]:
y

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [10]:
a,b,c = np.split(b,[1,3])

In [11]:
a

array([[1, 2, 3]], dtype=int32)

In [12]:
b

array([[4, 5, 6],
       [1, 2, 3]], dtype=int32)

In [13]:
c

array([[4, 5, 6]], dtype=int32)

In [14]:
bb = np.linspace(1,6,6,dtype=np.int32).reshape(2,3)

In [15]:
bb

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [16]:
h1, h2 = np.split(bb,[2],axis=1)

In [17]:
h1

array([[1, 2],
       [4, 5]], dtype=int32)

In [18]:
h2

array([[3],
       [6]], dtype=int32)

In [19]:
v1 = np.array([[1,2,3],[4,5,6]])

In [20]:
v2 = np.array([[11,12,13],[14,15,16]])

In [21]:
v = np.vstack([v1,v2])

In [22]:
v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16]])

In [23]:
x,y = np.vsplit(v,[2])

In [24]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
y

array([[11, 12, 13],
       [14, 15, 16]])